// Code generated by go generate; DO NOT EDIT.

package api

// Agent method constants
const (
	MethodAuthenticate  = "authenticate"
	MethodInitialize    = "initialize"
	MethodSessionCancel = "session/cancel"
	MethodSessionLoad   = "session/load"
	MethodSessionNew    = "session/new"
	MethodSessionPrompt = "session/prompt"
)

// Client method constants
const (
	MethodSessionUpdate            = "session/update"
	MethodTerminalCreate           = "terminal/create"
	MethodTerminalOutput           = "terminal/output"
	MethodTerminalRelease          = "terminal/release"
	MethodTerminalWaitForExit      = "terminal/wait_for_exit"
	MethodFsReadTextFile           = "fs/read_text_file"
	MethodFsWriteTextFile          = "fs/write_text_file"
	MethodSessionRequestPermission = "session/request_permission"
)

// Protocol version
const ACPProtocolVersion = 1
